= Calendar message system
:source-highlighter: rouge
:icons: font

== Intro
This program is to help second language speakers to get some content every day.
The ideal is to ask a LLM to write a bunch of phrases in the language to learn
and to translate it to learner's mother tongue, create a heading with the
languages that will used, then save the file as `phrases.txt` in the `files`
folder.

The file `phrases.txt` *must* have the following structure:

[source]
----
Language 1|Language 2
Phrase 1|Translation 1
Phrase 2|Translation 2
----

What to observe:

* A heading indicating in which languages the phrases are: first the language to
  learn and to which language the sentences are being translated to. Examples:
  
[source]
----
Portuguese|English
----

or 

[source]
----
PT|EN
----

* From the second line on, the phrases and their corresponding translations.

* Please observe that is *mandatory* to use the *|* symbol as the separator
  between the language names and the phrases and their translations. If the |
  symbol is not used, the email will be formatted incorrectly.

== How to use this program properly

* First, clone this repository
* Second, rename the `auth.json.example` file to `auth.json`
* Modify the `auth.json` adding your email details and instructions in the
  file.

[WARNING]
====
This program was only tested with *iCloud* and *Gmail*. I can not guarantee
whether this will work with other services. Suggestions are welcome.
====

[CAUTION]
====
The password to be used is the app-specific password and not the email password
(the one normally used in the log in screen).
Instructions for the services:

https://support.apple.com/en-au/102654[iCloud]

https://support.google.com/accounts/answer/185833?hl=en[Google]
====

* Create inside the `files` folder the `phrases.txt` file following the
  instructions described in first block.

* Go to the folder where the `main.py` file is located and run:

[source,bash]
----
$ python main.py
----

Logs will be shown and also be saved in `./files/app.log` file.

* If everything went well, turn the `main.py` file into an executable using `chmod` and
  then make a symbolic link to `/usr/local/bin`, as follows:

[source, bash]
----
$ sudo ln -s <path>/main.py /usr/local/bin/
----

Where `path` refers to the full path where `main.py` is located. From now on
the program can be executed by:

[source,bash]
----
$ main.py
----

* Finally, create a cron job so that the program will be executed automatically . Use this
https://crontab.guru/[link] to help to set the cron job with the desired
frequency. The following cron job will run the job every day at 3:00AM:

[source]
----
0 3 * * * main.py
----

[NOTE]
====
This program deletes the phrase sent every time is run. If you are running the
program to test it, please keep a copy of the `phrases.txt` somewhere else and
then overwrite the file before putting it in production.

When the program reaches the last sentence, a warning
message will be added to the email so that the user can take action before the
next program execution.
====
